In [1]:
import numpy as np
import torch as th

In [2]:
# th.*Tensor?

In [3]:
def describe(x):
    print(f'Type: {x.type()}')
    print('---'*15)
    print(f'Shape/Size: {x.shape}')
    print('---'*15)
    print(f'Value(s): \n{x}')
    

## Exercises

### Exercise 1

In [4]:
a = th.Tensor(3,4)
print(a.shape)
a = a.unsqueeze(0)
print(a.shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])


### Exercise 2

In [5]:
a = a.squeeze(0)
print(a.shape)

torch.Size([3, 4])


### Exercise 3

In [6]:
a = th.randint(3, 7, (5,3))
a

tensor([[6, 3, 3],
        [5, 3, 3],
        [4, 3, 3],
        [4, 6, 4],
        [4, 5, 3]])

In [7]:
a = 3 + th.rand(5,3) * 4
a

tensor([[3.0421, 4.6878, 6.8575],
        [5.1329, 5.9672, 5.1757],
        [6.6468, 4.4138, 3.8348],
        [3.9982, 5.0403, 4.3018],
        [4.1897, 4.5923, 6.9837]])

### Exercise 4

In [8]:
a = th.randn(2,2)
a

tensor([[-1.7052, -0.5609],
        [-0.4670,  0.3018]])

In [9]:
a = th.rand(2,2).normal_(mean=0, std=1)
a

tensor([[ 0.9306,  1.5165],
        [-1.7169, -0.4907]])

### Exercise 5

In [10]:
a = th.Tensor([1,1,1,0,1])
a

tensor([1., 1., 1., 0., 1.])

In [16]:
a.nonzero()

tensor([[0, 0],
        [1, 0],
        [2, 0]])

In [17]:
th.nonzero(a)

tensor([[0, 0],
        [1, 0],
        [2, 0]])

### Exercise 6

In [18]:
a = th.rand(3, 1)
a

tensor([[0.8361],
        [0.3739],
        [0.0293]])

In [19]:
b = th.stack([a,a,a,a])
b

tensor([[[0.8361],
         [0.3739],
         [0.0293]],

        [[0.8361],
         [0.3739],
         [0.0293]],

        [[0.8361],
         [0.3739],
         [0.0293]],

        [[0.8361],
         [0.3739],
         [0.0293]]])

In [20]:
A = a.repeat([1,4])

### Exercise 7

In [21]:
th.bmm

<function _VariableFunctionsClass.bmm>

In [22]:
a = th.rand(3,4,5)
b = th.rand(3,5,4)

In [23]:
th.bmm(a, b)

tensor([[[1.8829, 1.9549, 1.3053, 1.2827],
         [1.4019, 1.4913, 0.7618, 0.9260],
         [1.2153, 0.9994, 0.9075, 0.9491],
         [1.9864, 1.5028, 1.5840, 1.4000]],

        [[1.8970, 1.5124, 1.7846, 2.3433],
         [1.4513, 1.3860, 1.4616, 1.9243],
         [1.4422, 1.0738, 1.5023, 1.5575],
         [1.7868, 1.2880, 1.3900, 2.4317]],

        [[1.0360, 1.5095, 1.6134, 1.1576],
         [0.3973, 0.5701, 0.8370, 0.4952],
         [0.7052, 0.9042, 1.7659, 1.0184],
         [1.0613, 1.3870, 2.1742, 1.5322]]])

### Excersie 8

In [24]:
a = th.rand(3,4,5)
b = th.rand(5,4)
b

tensor([[9.6599e-01, 7.8518e-01, 4.2743e-01, 8.5940e-01],
        [7.8828e-01, 9.0564e-01, 8.3990e-01, 6.2655e-01],
        [7.8321e-01, 5.8768e-01, 1.7625e-04, 2.8555e-01],
        [5.4471e-01, 6.6151e-01, 3.3440e-01, 9.1981e-01],
        [5.6630e-01, 3.3750e-01, 7.9485e-01, 7.1079e-01]])

In [25]:
b = b.expand([3,5,4])
b

tensor([[[9.6599e-01, 7.8518e-01, 4.2743e-01, 8.5940e-01],
         [7.8828e-01, 9.0564e-01, 8.3990e-01, 6.2655e-01],
         [7.8321e-01, 5.8768e-01, 1.7625e-04, 2.8555e-01],
         [5.4471e-01, 6.6151e-01, 3.3440e-01, 9.1981e-01],
         [5.6630e-01, 3.3750e-01, 7.9485e-01, 7.1079e-01]],

        [[9.6599e-01, 7.8518e-01, 4.2743e-01, 8.5940e-01],
         [7.8828e-01, 9.0564e-01, 8.3990e-01, 6.2655e-01],
         [7.8321e-01, 5.8768e-01, 1.7625e-04, 2.8555e-01],
         [5.4471e-01, 6.6151e-01, 3.3440e-01, 9.1981e-01],
         [5.6630e-01, 3.3750e-01, 7.9485e-01, 7.1079e-01]],

        [[9.6599e-01, 7.8518e-01, 4.2743e-01, 8.5940e-01],
         [7.8828e-01, 9.0564e-01, 8.3990e-01, 6.2655e-01],
         [7.8321e-01, 5.8768e-01, 1.7625e-04, 2.8555e-01],
         [5.4471e-01, 6.6151e-01, 3.3440e-01, 9.1981e-01],
         [5.6630e-01, 3.3750e-01, 7.9485e-01, 7.1079e-01]]])

In [26]:
th.bmm(a, b)

tensor([[[2.7356, 2.5761, 1.8123, 2.5351],
         [2.3317, 2.0892, 1.2887, 1.9173],
         [2.1267, 1.7333, 1.2061, 1.9011],
         [2.0775, 1.9967, 1.2591, 1.7998]],

        [[2.6090, 2.4335, 1.7244, 2.4674],
         [1.9080, 1.8943, 1.2773, 1.9382],
         [1.0907, 1.0082, 0.7855, 1.3060],
         [1.8355, 1.5568, 0.8499, 1.3314]],

        [[1.3889, 1.1852, 0.9879, 1.1967],
         [1.4873, 1.2068, 1.2782, 1.4116],
         [1.1377, 1.0762, 0.7829, 0.9884],
         [1.4304, 1.2901, 0.7798, 1.2164]]])