<a href='https://aims-senegal.org/'> <img src='http://sn.nexteinstein.org/wp-content/uploads/sites/12/2016/07/aims_senegal.jpg' /></a>

In [3]:
# run this cell first
import numpy as np



---



---



---



# Exercise A:




### 1- Construct a Ndarray  of shape (3, 2) filled with **8**, Then set element (0, 1) to 10, and element (1, 0) to 100

In [5]:
################################################################################
#                              START OF YOUR CODE                              #
################################################################################

arr1 = np.ones((3,2))*8
arr1[0,1] = 10
arr1[1,0] = 100
arr1

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[  8.,  10.],
       [100.,   8.],
       [  8.,   8.]])

### 2- Create a 64-bit floating-point Ndarray of shape (6,) (six-element vector) filled with evenly-spaced values between 10 and 20. 

In [6]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

arr2 = np.linspace(10, 20, 6)
arr2
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([10., 12., 14., 16., 18., 20.])

### 3- Create a vector with values ranging from 10 to 49

In [7]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

vec1 = np.arange(10,49)
vec1
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

### 4- Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

mat1 = np.arange(0,9).reshape(3,3)
mat1
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 5- Create a 10x10 array with random values and print the trace value and the mean values of each row

In [13]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

mat2 = np.random.random((10, 10))
print(f'Trace = {mat2.trace()}')
print(f'Mean = {mat2.mean()}')
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

Trace = 4.9399250579100356
Mean = 0.44372629599671093


### 6- Create a Ndarray array of size (5, 5) with all **1** on the borders and all **0** in the inside


In [32]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

mat3 = np.ones((5,5))
mat3[1:-1, 1:-1] = 0
mat3
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 7- Create random vector of size 10 and replace the maximum value by 0

In [25]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

vec2 = np.random.random(10)
print(f'Before: {vec2}')
vec2[vec2.argmax()] = 0
print(f'After: {vec2}')
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

Before: [0.01112651 0.6911958  0.27634461 0.93414111 0.25298523 0.10947483
 0.15170078 0.24989654 0.05564231 0.52120859]
After: [0.01112651 0.6911958  0.27634461 0.         0.25298523 0.10947483
 0.15170078 0.24989654 0.05564231 0.52120859]


### 8- Normalize a 5x5 random matrix
Hint: subtract the mean and devide by the standard deviation

In [31]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################

mat = np.random.random(25).reshape(5,5)
μ = mat.mean()
σ = mat.std()
print(f'Matrix:\n{mat}\n')
print(f'Matrix mean: {μ}')
print(f'Matrix std: {σ}\n')

mat -= μ
mat /= σ
print(f'Normalized Matrix:\n{mat}')
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

Matrix:
[[0.25712529 0.86526633 0.43551537 0.0187545  0.32825986]
 [0.64133877 0.70857774 0.5722337  0.34376358 0.20000062]
 [0.02023785 0.94529694 0.28888614 0.35327856 0.90400893]
 [0.74514483 0.23013841 0.1758491  0.13837537 0.34149754]
 [0.45135127 0.38281584 0.09497543 0.63887769 0.16177666]]

Matrix mean: 0.4097338532821202
Matrix std: 0.26851917119483676

Normalized Matrix:
[[-0.56833397  1.69646166  0.0960137  -1.4560575  -0.30341965]
 [ 0.86252657  1.11293315  0.60517037 -0.2456818  -0.7810736 ]
 [-1.45053331  1.99450596 -0.45005247 -0.21024677  1.8407441 ]
 [ 1.24911371 -0.66883657 -0.87101698 -1.01057398 -0.25412082]
 [ 0.15498864 -0.10024614 -1.17220092  0.85336119 -0.92342456]]


### 9- Create a random 5x2 matrix representing cartesian coordinates and print an array **"polar"** with same shape representing the converted polar coordinates.

Hints:

X represent the first column.

Y represent the second column.

Compute:

$$ R = \sqrt{X^2 + Y^2} $$

$$ T = \arctan{(Y, X)} $$


In [39]:
################################################################################
#                              START OF YOUR CODE                              #
################################################################################

coor_cart = np.random.random(10).reshape(5,2)
coor_pol = np.zeros_like(coor_cart)
coor_pol[:,0] = np.sqrt(coor_cart[:,0]**2 + coor_cart[:,1]**2)
coor_pol[:,1] = np.arctan2(coor_cart[:,1], coor_cart[:,0])
print(f'Cartesian coordinates (X,Y):\n{coor_cart}\n')
print(f'Polar coordinates (R,T):\n{coor_pol}')

################################################################################
#                              END OF YOUR CODE                                #
################################################################################

Cartesian coordinates (X,Y):
[[0.35676592 0.74801   ]
 [0.90273853 0.09100211]
 [0.13737516 0.94219633]
 [0.83866508 0.41281586]
 [0.63862923 0.07016537]]

Polar coordinates (R,T):
[[0.82873451 1.12575539]
 [0.90731375 0.10046732]
 [0.95215852 1.42601341]
 [0.93475989 0.45741207]
 [0.64247216 0.1094298 ]]




---



---



---



### 10- Write a function that normalizes the columns of a matrix. It should compute the mean and standard deviation of each column, then subtract the mean and divide by the standard deviation for each element in the column. 

Example:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- The first column has mean 0 and std 1
- The second column has mean 20 and std 10
- The third column has mean 400 and std 200

After normalizing the columns, the result should be:
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

Your implementation should not use any loops; instead you should use reduction and broadcasting operations.

In [64]:


################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def normalize_columns(x0):

  # x: (input) Ndarray of shape (N, M) (don't modefy it: use copy())
  # y: (return) Ndarray of shape (N, M) normalized by the columns
  x = x0.copy()
  μ = x.mean(axis=0)
  σ = x.std(axis=0)
  x -= μ
  x /= σ
  return x
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [65]:
# x0 = np.array([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
# print(f'x0 =\n {x0}')
# print(f'Mean = {x0.mean(axis=0)}')
# print(f'STD = {x0.std(axis=0)}')

In [67]:
x0 = np.array([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
print('Here is x0:')
print(x0)
y0 = normalize_columns(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1.224744871391589, 1.224744871391589], [1.224744871391589, -1.224744871391589, -1.224744871391589], [-1.224744871391589, 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]

Here is x0:
[[  0.  30. 600.]
 [  1.  10. 200.]
 [ -1.  20. 400.]]
Here is y0:
[[ 0.          1.22474487  1.22474487]
 [ 1.22474487 -1.22474487 -1.22474487]
 [-1.22474487  0.          0.        ]]




---



---



---



### 11- creates a function that returns a matrix of **one-hot vectors** from a list of Python integers. A one-hot vector for an integer $n$ is a vector that has a one in its $n$th slot, and zeros in all other slots. One-hot vectors are commonly used to represent categorical variables in machine learning models.

### For example, given a list `[1, 4, 3, 2]` of integers, your function should produce the tensor:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

### Here the first row corresponds to the first element of the list: it has a one at index 1, and zeros at all other indices. The second row corresponds to the second element of the list: it has a one at index 4, and zeros at all other indices. The other rows follow the same pattern. 

In [60]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def make_one_hot(x):

  #x: (input) A list of n ints

 

  dim1 = np.max(x) + 1
  dim0 = len(x)
  mat = np.zeros((dim0, dim1))
  print(mat.shape)
  #print(dim0)
  print(np.arange(dim1))
  
  mat[np.arange(dim0),x] = 1

  return mat
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [61]:
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)

(4, 5)
[0 1 2 3 4]


In [62]:
y0

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

Run the following cell to check your implementation, you must see 'all checks pass!' message

In [66]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

(4, 5)
[0 1 2 3 4]
Here is y0:
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
(6, 8)
[0 1 2 3 4 5 6 7]

Here is y1:
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
all checks pass!




---



---



---



# Exercise B:

### Maximum Likelihood
Find the maximum likelihood estimation of parameters $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N
$$

Steps to follow:


1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Compute the maximum likelihood estimation of parameters $\boldsymbol\theta$ following the equation and assign it to a variable called **theta**

$$
\boldsymbol\theta = (\boldsymbol X^T\boldsymbol X)^{-1}\boldsymbol X^T\boldsymbol y\in\mathbb{R}^D
$$

4. print the value of **theta**

Hint: check the inverse method from the linear algebra module in Numpy

In [72]:
################################################################################
# TODO: Compute the maximum likelihood estimation of parameters theta
#       following the equation
################################################################################
N = 10
D = 5
X = np.random.randn(N*D).reshape(N,D) # 10x5
X_T = X.transpose() # 5x10
y = np.ones((N,1)) # 10x1

A = np.linalg.inv(X_T.dot(X)) # 5X5
B = X_T.dot(y) # 5x1
θ = np.dot(A,B) # 5x1
print(θ)
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

array([[ 0.26978863],
       [ 0.27339524],
       [ 0.39627346],
       [-0.19975956],
       [-0.44192347]])



---



---



---



# Exercise C:

### The Log Likelihood

Find the log likelihood estimation for input X, label y, parameterized by $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N \quad \boldsymbol \theta  \in\mathbb{R}^D
$$

steps to follow:

1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Initialize Ndarray **theta** randomly with shape D = 5 and reshape it to have the shape (D, 1).
4.   Compute the the probability of a all data points $(\boldsymbol x, y)$ being of class 1, given by

$$p(y = 1 | \boldsymbol X, \boldsymbol\theta) = 1.0/(1.0+\exp(- \boldsymbol X \boldsymbol \theta))$$

5. compute the log Likelihood, given by:
$$\log p(\boldsymbol y|\boldsymbol X, \boldsymbol\theta) = \sum_i y_i * \log (p(y = 1 | \boldsymbol x, \boldsymbol\theta)) + (1 - y_i) * \log ( 1 - p(y = 1 | \boldsymbol x, \boldsymbol\theta))$$

6. print the log Likelihood

In [83]:
N = 10
D = 5

X = np.random.randn(N,D) # 10x5
y = np.ones((N,1)) # 10x1
𝜽 = np.random.randn(D).reshape(D,1)

P = 1./(1. + np.exp(-np.dot(X,𝜽)))
print(f'Probability =\n{P}\n')

LL = np.sum( y*np.log(P) + (1-y)*np.log(1-P) )
print(f'Log Likelihood Probability =\n{LL}')

Probability =
[[0.64165063]
 [0.07390846]
 [0.31271023]
 [0.99864198]
 [0.99070833]
 [0.56158835]
 [0.51932207]
 [0.91752148]
 [0.12651763]
 [0.6286073 ]]

Log Likelihood Probability =
-8.071730343686442


In [73]:
################################################################################
# TODO: Compute the log likelihood 
#    
################################################################################


#your code should be here

X = np.random.randn(10, 5)
y = np.ones((10,1))
theta = np.random.random((5, 1))

p = 1.0/(1 + np.exp(-X @ theta))
L = np.sum(y*np.log(p) + (1 - y)*np.log(1 - p))

print(L)
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

-9.30393638442617
